### ISSUE TITLE
Keep toolbar always on top ?

### ISSUE THREAD

**Issue by Kintaro37** [PSD-Company/duo-navigation-drawer#10]
Hello,
First of all, thank you for sharing your work. Also, here is a question, not an issue report.

Is there a possibility to keep the toolbar always visible on top, so that on the hamburger click, the menu drawer slides **below** the toolbar?

**Comment by Alexander-1504** [comment]
Yes this is possible, just put a toolbar outside the DuoDrawerLayout.

Example:

```xml
<LinearLayout>
    <android.support.v7.widget.Toolbar/>
    <nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout>
        <nl.psdcompany.duonavigationdrawer.views.DuoMenuView/>
        <FrameLayout/>
    </nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout>
</LinearLayout>
```
