### ISSUE TITLE
Navigation drawer not working properly in tablets. 

### ISSUE THREAD

**Issue by perasoft** [PSD-Company/duo-navigation-drawer#11]
I have tested it in a real device Nokia N1 and also in an emulator Nexus 9. It seems that when the drawer is open its hard to close it, and also the menus are not clickable. Please fix this issue as I really like this drawer it works perfectly in phones I have tested it in Nexus 6p (real device) and also Nexus 5 (real device) and a bunch of emulators. Thanks.

**Comment by Alexander-1504** [comment]
I don't have time to work on this library right now. I'll work on it in the near future. Maybe you can look at the problem yourself and create a pull request.

**Comment by cuberob** [comment]
Just ran into the same issue, tested with the sample app provided by you as well and seeing the same issue (Nexus 9 emulator - API 23). Having some trouble figuring out what's actually causing the issue, but if I do stumble across is I'll get back here... If anyone else has any ideas please share! :)
