### ISSUE TITLE
How can I change the color of a toggle?

### ISSUE THREAD

**Issue by danJarNC** [PSD-Company/duo-navigation-drawer#13]

**Comment by Alexander-1504** [comment]
Hi,

If you enabled the hamburger icon via ActionBarDrawerToggle. You should look at: https://developer.android.com/reference/android/support/v4/app/ActionBarDrawerToggle.html

To change the hamburger icon you can call the setHomeAsUpIndicator() method on the toggle instance. If you change the icon the animation won't work anymore. Same as the default android menu. 

If you want to keep the animation but only change the color of the hamburger icon. You can do that with a custom style. Again, same as the default android menu.

**Comment by Alexander-1504** [comment]
Did u manage to solve your problem?
