### ISSUE TITLE
How to change name(John Duo) and employeer designation

### ISSUE THREAD

**Issue by kingnightdrifter** [PSD-Company/duo-navigation-drawer#14]
Hello I add one image in header also i want to change the header name and designation where is its support?

**Comment by Alexander-1504** [comment]
Just add your own header layout to the menu view.

```xml
<nl.psdcompany.duonavigationdrawer.views.DuoMenuView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:tag="@string/tag_menu"
    app:footer="@layout/view_footer"
    app:header="{your layout}"
    ... />
```

**Comment by kingnightdrifter** [comment]
ok now i understand but how to call this layout and past my own text in it dynamically...

**Comment by Alexander-1504** [comment]
This is the view you want to adjust:

https://github.com/PSD-Company/duo-navigation-drawer/blob/master/duo-navigation-drawer/src/main/res/layout/duo_view_header.xml

**Comment by kingnightdrifter** [comment]
No I did not
