### ISSUE TITLE
Not able to hide floating action button when drawer is opened

### ISSUE THREAD

**Issue by mdhaider** [PSD-Company/duo-navigation-drawer#16]
I have added floating button in my main activity and want to hide when drawer is opened

**Comment by Alexander-1504** [comment]
Create your own [DuoDrawerToggle](https://github.com/PSD-Company/duo-navigation-drawer/blob/master/duo-navigation-drawer/src/main/java/nl/psdcompany/duonavigationdrawer/widgets/DuoDrawerToggle.java) and hide when onDrawerOpened() is called.
