### ISSUE TITLE
Drop shadow below the content view

### ISSUE THREAD

**Issue by vipulpurohit** [PSD-Company/duo-navigation-drawer#17]
Hello
Thanks for this library.
Is there any way we can add drop shadow below the content with when navigation drawer is open?
Like the image below: 

![image](https://user-images.githubusercontent.com/5219201/35858413-551d41fe-0b62-11e8-9787-9a767ef83df9.png)

**Comment by kaiyan910** [comment]
you can add elevation attribute to the content view but only work for SDK > 21

**Comment by Alexander-1504** [comment]
You can customize the content view yourself.
