### ISSUE TITLE
How to "replace" fragment not to "add" in goToFragment()

### ISSUE THREAD

**Issue by gaiththewolf** [PSD-Company/duo-navigation-drawer#22]
all my fragment superposed in one page when i change
` transaction.add(R.id.container, fragment).commit();`
to
`transaction.replace(R.id.container, fragment).commit();`

application crash with error : 

> No view found for id 0x7f090054 (com.packa...:id/content) for fragment SFrag{48bbddc #8 id=0x7f090054}

help please

**Comment by gaiththewolf** [comment]
done!

**Comment by 1cornerstone** [comment]
Weldone, i also encounter this error( fragment  keep changing  to the first  fragment  view when i click on another fragment view).  I got it solved ,  i just want to pull request i saw your solution. Salute

<img width="723" alt="Screen Shot 2019-06-06 at 6 39 42 PM" src="https://user-images.githubusercontent.com/22201154/59053950-7f0e0380-888a-11e9-87a2-e61519c93bd7.png">
