### ISSUE TITLE
Background Color of Navigation Drawer

### ISSUE THREAD

**Issue by mhafeezgr8** [PSD-Company/duo-navigation-drawer#28]
Hey its a question not an issue, i have just noticed that navigation drawer background color is being picked up from of toolbar of extending activity, so if there's a way we can  customize the background color of navigation drawer

**Comment by AsadLeo14** [comment]
@mhafeezgr8 use app:background="@drawable/bg" attribute

<nl.psdcompany.duonavigationdrawer.views.DuoMenuView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        **app:background="@drawable/bg"**
        />
