### ISSUE TITLE
not able to catch hamburger icon click event 

### ISSUE THREAD

**Issue by ZeroCool00** [PSD-Company/duo-navigation-drawer#4]
its work fine before i implement duo-navigation-drawer, now i m not able to get home button click event, its like drawer has total control of toolbar. we cant do anything without getting context of drawer, if i remove drawer toolbar works fine.. i m able change icon and everything. with drawer i m getting default hamburger icon, event if i set manually its not changing.

**Comment by Alexander-1504** [comment]
This is the desired behaviour of the DuoDrawerToggle which is a copy of the android drawer toggle. If you want to catch navigation item click events and keep the functionalities of the drawer toggle. You should probably override the click listener in the drawer toggle. You can do this by calling drawerToggle.setToolbarNavigationClickListener();

I hoped this helped and solved your problem.
