### ISSUE TITLE
keystore Properties the system cannot find the file specified 

### ISSUE THREAD

**Issue by dondeepak** [PSD-Company/duo-navigation-drawer#6]
i am getting error says how do i fix this??
Error:(6, 0) D:\Android\duo-navigation-drawer-master\keystore.properties (The system cannot find the file specified)
<a href="openFile:D:\Android\duo-navigation-drawer-master\app\build.gradle">Open File</a>

**Comment by SeaRoth** [comment]
Delete it then run it big guy

![image](https://user-images.githubusercontent.com/3461713/29737517-a69e1fba-89c3-11e7-98a4-45a4992cdb07.png)

**Comment by dondeepak** [comment]
thank you

**Comment by Alexander-1504** [comment]
Glad someone else helped you. I will change this soon and update my library.

**Comment by DkCloudAccount** [comment]
@SeaRoth  which file we have to delete  help plz

**Comment by SeaRoth** [comment]
Compare my image of the gradle to yours and delete the extraneous info like keystore

**Comment by DkCloudAccount** [comment]
yay i changed it thnkss
