### ISSUE TITLE
Item Selected Side Drawable

### ISSUE THREAD

**Issue by Mina-Mikhail** [PSD-Company/duo-navigation-drawer#7]
![img_20170730_232415](https://user-images.githubusercontent.com/17712116/28757964-8eca8dc2-758e-11e7-8089-c772fe451b07.png)

I want to change the red color on the left side to another color, HOW can i do that please??

Thank you sir for this fantastic library

**Comment by Alexander-1504** [comment]
Unfortunately this is an image view. If you want to change this view you have to call the third bind method inside the option view. This bind method has three parameters. The last param is the drawable you want. You could also skip the entire option view and use your own.
